Fix nightly test (#915)
Nightly tests are failing with this error:
> Error: Did not find quick pick item matching '$(plus) Create new storage account'. Placeholder: 'Select a runtime for your new app.'

We now prompt for runtime if they don't have the project language set, which broke the test. I think it's more common to have the language set, so I went with that scenario to fix.